spring:
  application:
    name: mcpserverstdio # Application name used for identification

  datasource:
    url: jdbc:h2:file:~/chatmemory;AUTO_SERVER=true # H2 database file location and server mode
    driver-class-name: org.h2.Driver # JDBC driver for H2 database
    username: madan # Database username
    password: 12345 # Database password

  h2:
    console:
      enabled: true # Enables H2 web console for database inspection

  jpa:
    hibernate:
      ddl-auto: update # Automatically update DB schema based on entities

  main:
    web-application-type: none # No embedded web server (for CLI or background tasks)
    banner-mode: off # Disables Spring Boot startup banner

logging:
  level:
    root: ERROR # Sets root logger level to ERROR (suppresses INFO, WARN, DEBUG logs)

weather:
  url-template: "https://wttr.in/%s?format=j1" # URL template for weather API requests; can be used by the MCP client to fetch weather data asynchronously.
  